name: GitHub actions nodejs

on:
  push:
    branches: ["main"]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Install node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: "npm install"
